### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by HarishSonar** [mafintosh/is-my-json-valid#155]
After 2.17.0 release we are getting issue
Module build failed: TypeError: Cannot read property 'concat' of undefined
\node_modules\is-my-json-valid\index.js:366:69)

**Comment by LinusU** [comment]
Hello, this was an error in version `2.17.0` and has now been fixed in `2.17.1`, see #149 for more details. Sorry for any inconvenience.

**Comment by matheusgrieger** [comment]
I am still getting this error on `2.17.1`. Here is the full log output:
```
Module build failed: TypeError: Cannot read property 'concat' of undefined
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:366:70)
    at /home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (<anonymous>)
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:409:18)
    at /home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (<anonymous>)
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:340:16)
    at /home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (<anonymous>)
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:409:18)
    at /home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (<anonymous>)
    at visit (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/home/matheus/Projetos/agrogestaoweb/pwa_client/node_modules/eslint/node_modules/is-my-json-valid/index.js:565:3)
```

I double-checked and the installed version is, indeed, `2.17.1`...
